# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Clear' do
    pod 'Firebase', '>= 2.2.0'
    pod 'SVProgressHUD'
    pod 'OpenSans'
end

target 'ClearTests' do

end

